[package]
name = "friendly-zoo"
version = "0.1.0"
authors = ["Tronje Krabbe <hi@tron.je>"]
edition = "2018"
description = "A simple crate to generate random animal names"
license = "Unlicense"
repository = "https://github.com/tronje/friendly-zoo"

[dependencies]
rand = "0.7.3"
